# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dllanes- <dllanes-@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/07/27 17:44:05 by dllanes-          #+#    #+#              #
#    Updated: 2022/07/27 20:04:06 by dllanes-         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = bsq

SRC = bsq.c

$(NAME):
	@gcc -Wall -Werror -Wextra -o $(NAME) $(SRC)
clean:
	@rm -f *.o
fclean: clean
	@rm -f $(NAME)
